### ISSUE TITLE
Classify anoxygenic phototrophs

### ISSUE THREAD

**Issue by ckeuschn** [jgoldford/aerobot#4]
Hi, 

I was trying to classify several MAGs of anoxygenic phototrophs and reference genomes. These bacteria can live aerobically (for example in the surface waters of the ocean) or anaerobically (in deeper waters in lakes). However, the tool classified all genomes put in as anaerobes, also the known aerobic ones. Any thoughts on this and can I proviode a training dataset with knows aerobic anoxygenic phototrophs to this maybe? Thanks a lot for any help
Cheers
Christoph

**Comment by pipparichter** [comment]
Hello! Do you mind sending me the code you used to generate the predictions + the MAG data? I can see if I can figure out what's going on!

Best,

Pippa

**Comment by ckeuschn** [comment]
Hi, thanks for your reply. 

I simply ran : python  aerobot.py  AP_MAG_1_prot.faa  > aerobot_predictions.csv

The .faa file contains amino acid sequences of predicetd genes from the MAG

I can send you a link to download all ref genomes and MAG data when you send me an email maybe? 

Best, 
Ch

**Comment by pipparichter** [comment]
Sure! Can you email me the link at prichter@caltech.edu?

**Comment by pipparichter** [comment]
Hello! It seems like the files you sent me are nucleotide sequences, not amino acids

**Comment by ckeuschn** [comment]
Hello! Yes you are right, that was a error in my script exporting the ORFs. I get classifications now and will check if they fit the physiology of the reference genomes. All MAGs are classified aerobes which is what I expected. 

Thanks a lot for your help and sorry again for not noticing that!
Best
Ch
